//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DClubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int id_request { get; set; }
        public System.DateTime Request_Date { get; set; }
        public int id_account { get; set; }
        public int id_status { get; set; }
        public int id_club { get; set; }
        public int id_group { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Clubs Clubs { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Status Status { get; set; }
    }
}
