//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DClubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int id_schedule { get; set; }
        public string Schedule_DayOfWeek { get; set; }
        public string Schedule_StartTime { get; set; }
        public string Schedule_EndTime { get; set; }
        public int id_group { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
